# Generated by Django 5.1.2 on 2024-10-20 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customer_state_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='locality',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='zipcode',
            new_name='postcode',
        ),
    ]
